### ISSUE TITLE
Show selected template on subportals for host user

### ISSUE THREAD

**Issue by sourabhmalani** [DNNCommunity/DNN.Newsletter#4]
Hello Team,

We are using Newsletter module on our website. We have multiple portals setup on our website.

On the main portal in the description section host user can save the template and select the saved template then it show the details of that template.

But if host user perform this action on sub portals then he can save the template but if he select the template then it will not show that content and also while selecting template it will not show content in the preview section.

so template selection functionality working properly on main portal, but for sub portals it is not working as main portal.

![ss_01](https://cloud.githubusercontent.com/assets/7112894/24506135/155ac6ce-157a-11e7-9869-c898db7348dc.jpg)
![ss_02](https://cloud.githubusercontent.com/assets/7112894/24506134/155a1a58-157a-11e7-8b14-02b718a8e6ae.jpg)

Please help us to resolve this issue.

Thank you in advance.

Best Regards,
Sourabh Malani

**Comment by david-poindexter** [comment]
@sourabhmalani I just found your issue here and I am sorry nobody has responded yet.  In short, this is more of an editor provider question for the [DNN Platform](https://github.com/dnnsoftware/DNN.Platform) project rather than this **DNN.Newsletter** module project.  If your question is still valid/pending, please consider opening an issue there.  Thanks!
